name: Attack
version: ${project.version}
main: com.seailz.attack.AttackPlugin
api-version: 1.18
authors: [ Seailz ]
description: Attack - A custom island minigame where blocks slowly disappear.
website: www.seailz.com
